events {}

http {
  upstream app1_backend { server app1:8080; }
  upstream app2_backend { server app2:8080; }

  server {
    listen 80;

    # http://localhost/app1/hello -> app1:8080/hello
    location /app1/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

      rewrite ^/app1/(.*)$ /$1 break;
      proxy_pass http://app1_backend;
    }

    # http://localhost/app2/hello -> app2:8080/hello
    location /app2/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

      rewrite ^/app2/(.*)$ /$1 break;
      proxy_pass http://app2_backend;
    }
  }
}